version: '3'
services:
  openfaas:
    image: vv6294/filenamegenerator
  fastapi:
    image: vv6294/fastapiimage
    ports:
      - "8000:8000"
  frontend:
    image: vv6294/reactimage
    ports:
      - "80:3000"